---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsubnets.demo.io
spec:
  group: demo.io
  defaultCompositionRef:
    name: xsubnets.demo.io
  names:
    kind: XSubnet
    plural: xsubnets
    singular: xsubnet
  claimNames:
    kind: Subnet
    plural: subnets
    singular: subnet
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - cidrs
                - subscriptionId
              properties:
                cidrs:
                  description: 'cidrs: Subnets cidrs'
                  type: array
                  items:
                    type: string
                subscriptionId:
                  description: 'subscriptionId: Subnets subscription Id '
                  type: string
