---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaccounts.demo.io
spec:
  group: demo.io
  defaultCompositionRef:
    name: xsubscription.demo.io
  names:
    kind: XAccount
    plural: xaccounts
    singular: xaccount
  claimNames:
    kind: Account
    plural: accounts
    singular: account
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                subscriptionID:
                  description: 'Id of subscription'
                  type: string
                accountType:
                  description: 'Account Type Possible values: standard, premium, enterprise'
                  type: string
                  enum:
                    - standard
                    - premium
                    - enterprise
            status:
              type: object
              properties:
                subscriptionID:
                  type: string
                  description: 'Subscription ID'
                accountComposedName:
                  type: string
                  description: 'Subscription composed name'