---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsubscriptions.demo.io
  labels:
    demo.io/cloud-provider: azure
spec:
  compositeTypeRef:
    apiVersion: demo.io/v1alpha1
    kind: XAccount
  resources:
    - name: customer-provider
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ProviderConfig
        metadata:
          name:  # patched
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              name: azure-creator
              key: credentials
          subscriptionID:  # patched
      readinessChecks:
        - type: None
      patches:
        - fromFieldPath: spec.subscriptionID
          toFieldPath: metadata.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.subscriptionID
          toFieldPath: spec.subscriptionID
          policy:
            fromFieldPath: Required
    - name: register-provider-network
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceProviderRegistration
        metadata:
          name:  # patched
        spec:
          forProvider:
            name: Microsoft.Network
          providerConfigRef:
            name:  # patched
      patches:
        - fromFieldPath: spec.subscriptionID
          toFieldPath: spec.providerConfigRef.name
          policy:
            fromFieldPath: Required
    - name: register-provider-sql
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceProviderRegistration
        metadata:
          name:  # patched
        spec:
          forProvider:
            name: Microsoft.Sql
          providerConfigRef:
            name:  # patched
      patches:
        - fromFieldPath: spec.subscriptionID
          toFieldPath: spec.providerConfigRef.name
          policy:
            fromFieldPath: Required
    - name: resource-provider-registration-usage
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: azure.upbound.io/v1beta1
            kind: ProviderConfig
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: azure.upbound.io/v1beta1
            kind: ResourceProviderRegistration
            resourceSelector:
              matchControllerRef: true